
var NomeTabela

function pageSetUpTable(i) {
    alert(i);
    NomeTabela = i;
}



/* // DOM Position key index //

l - Length changing (dropdown)
f - Filtering input (search)
t - The Table! (datatable)
i - Information (records)
p - Pagination (paging)
r - pRocessing
< and > - div elements
<"#id" and > - div with an id
<"class" and > - div with a class
<"#id.class" and > - div with an id and class

Also see: http://legacy.datatables.net/usage/features
*/

var responsiveHelper_datatable_col_reorder = undefined;

var breakpointDefinition = {
    tablet: 1024,
    phone: 480
};

var cod_cliente = document.getElementById("cod_cliente").value;

var url = "/GarantiaItem/ReadItemJsUsingSqlAndView/" + cod_cliente;


/* COLUMN SHOW - HIDE */
var otable = $('#datatable_col_reorder').dataTable({

    // Tabletools options:
    //   https://datatables.net/extensions/tabletools/button_options
    "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'><'col-sm-6 col-xs-6 hidden-xs'TC>r>" +
            "t" +
            "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
    "oTableTools": {
        "aButtons": [
        "copy",
        "csv",
           {
               "sExtends": "print",
               "sMessage": "Generated by CRM <i>(press Esc to close)</i>"
           }
        ],
        "sSwfPath": "/Scripts/plugin/datatables/swf/copy_csv_xls_pdf.swf"
    },
    "autoWidth": true,
    "preDrawCallback": function () {
        // Initialize the responsive datatables helper once.
        if (!responsiveHelper_datatable_col_reorder) {
            responsiveHelper_datatable_col_reorder = new ResponsiveDatatablesHelper($('#datatable_col_reorder'), breakpointDefinition);
        }
    },
    "rowCallback": function (nRow) {
        responsiveHelper_datatable_col_reorder.createExpandIcon(nRow);
    },
    "drawCallback": function (oSettings) {
        responsiveHelper_datatable_col_reorder.respond();
    },
    "bServerSide": true,
    "sAjaxSource": url,
    "searchDelay": 2000,
    "bProcessing": true,
    "pageLength": 10,
    //"ordering": false,
    "columnDefs": [
  { targets: 'no-sort', orderable: false }
    ],
    "aoColumns": [
                   { "sName": "dta_lancamento" },
                   { "sName": "cod_foxlux" },
                   { "sName": "des_item", "mRender": function (data, type, full) { return '<a href=\"#' + full[1] + '\">' + full[2] + '</a>'; } },
                   { "sName": "qtd_lancamento" },
                   { "sName": "num_documento" },
                   { "sName": "vlr_unitario" },
                   { "sName": "vlr_total" },
                   { "sName": "vlr_ipi" },
                   { "sName": "vlr_icms_subs" },
                   { "sName": "dias" }


    ]
});


// Apply the filter
$("#datatable_col_reorder thead th input[type=text]").on('keyup change', function () {
    otable
        .column($(this).parent().index() + ':visible')
        .search(this.value)
        .draw();

});
