
    
    function pageSetUpTable(Nome, LenPaginas) {
    LenPaginas = LenPaginas || 10;


    var responsiveHelper_datatable_col_reorder = undefined;

    var breakpointDefinition = {
        tablet: 1024,
        phone: 480
    };

    var objeto = '#' + Nome;


    /* COLUMN SHOW - HIDE */
    var otable = $(objeto).dataTable({
        //"bFilter": false,
        //"bInfo": false,
        //"bLengthChange": false
        //"bAutoWidth": false,
        //"bPaginate": false,
        //"bStateSave": true // saves sort state using localStorage
        // Tabletools options:
        //   https://datatables.net/extensions/tabletools/button_options
        "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>" +
                "t" +
                "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
        "oTableTools": {
            "aButtons": [
            "copy",
            "csv",
               {
                   "sExtends": "print",
                   "sMessage": "Generated by CRM <i>(press Esc to close)</i>"
               }
            ],
            "sSwfPath": "/Scripts/plugin/datatables/swf/copy_csv_xls_pdf.swf"
        },
        "autoWidth": true,
        "preDrawCallback": function () {
            // Initialize the responsive datatables helper once.
            if (!responsiveHelper_datatable_col_reorder) {
                responsiveHelper_datatable_col_reorder = new ResponsiveDatatablesHelper($(objeto), breakpointDefinition);
            }
        },
        "rowCallback": function (nRow) {
            responsiveHelper_datatable_col_reorder.createExpandIcon(nRow);
        },
        "drawCallback": function (oSettings) {
            responsiveHelper_datatable_col_reorder.respond();
        },
        //"bProcessing": true,
        "pageLength": LenPaginas
        //,"oLanguage": { "sZeroRecords": "", "sEmptyTable": "" }
    });



}

    function pageSetUpTableSearch(Nome, LenPaginas) {
        LenPaginas = LenPaginas || 10;
        


        var responsiveHelper_datatable_col_reorder = undefined;

        var breakpointDefinition = {
            tablet: 1024,
            phone: 480
        };

        var objeto = '#' + Nome;


        /* COLUMN SHOW - HIDE */
        var otable = $(objeto).dataTable({
            //"bFilter": false,
            //"bInfo": false,
            //"bLengthChange": false
            //"bAutoWidth": false,
            //"bPaginate": false,
            //"bStateSave": true // saves sort state using localStorage
            // Tabletools options:
            //   https://datatables.net/extensions/tabletools/button_options
            "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'><'col-sm-6 col-xs-6 hidden-xs'>r>" +
                    "t" +
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
            //"oTableTools": {
            //    "aButtons": [
            //    "copy",
            //    "csv",
            //       {
            //           "sExtends": "print",
            //           "sMessage": "Generated by CRM <i>(press Esc to close)</i>"
            //       }
            //    ],
            //    "sSwfPath": "/Scripts/plugin/datatables/swf/copy_csv_xls_pdf.swf"
            //},
            //"autoWidth": true,
            //"preDrawCallback": function () {
            //    // Initialize the responsive datatables helper once.
            //    if (!responsiveHelper_datatable_col_reorder) {
            //        responsiveHelper_datatable_col_reorder = new ResponsiveDatatablesHelper($(objeto), breakpointDefinition);
            //    }
            //},
            //"rowCallback": function (nRow) {
            //    responsiveHelper_datatable_col_reorder.createExpandIcon(nRow);
            //},
            //"drawCallback": function (oSettings) {
            //    responsiveHelper_datatable_col_reorder.respond();
            //},
            //"bProcessing": true,
            "pageLength": LenPaginas
        });



    }
